# Generated by Django 4.1.2 on 2022-10-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_image_delete_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
